version: '2'

services:
    got-rabbitmq:
        image: rabbitmq
        hostname: got-rabbitmq
        command: rabbitmq-server
        entrypoint: ""
        volumes:
            - ${GOT_DIR}/rabbitmq/data:/var/lib/rabbitmq
            - ${GOT_DIR}/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        environment:
            - RABBITMQ_DEFAULT_USER=got
            - RABBITMQ_DEFAULT_PASS=got

    got-mongo:
        image: mongo
        volumes:
            - ${GOT_DIR}/mongo:/data/db

    got-redis:
        image: redis
        volumes:
            - ${GOT_DIR}/redis:/data

    got-consul:
        image: consul
        hostname: consulnode1
        # To be remove in prod, used internally only
        ports:
            - "8400:8400"
            - "8500:8500"
        command: agent -dev -client 0.0.0.0 -log-level info

    got-traefik:
        # In production, port 8080 should not be open
        image: traefik
        ports:
                - "8080:8080"
                - "8081:80"
        volumes:
                - ${GOT_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml

    got-auth:
        image: osallou/goterra-auth
        depends_on:
            - got-consul
        environment:
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-mongo
            - got-consul

    got-store:
        image: osallou/goterra-store
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
        depends_on:
            - got-consul
            - got-redis
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
    
    got-deploy:
        image: osallou/goterra-deploy
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_AMQP=amqp://got:got@got-rabbit:5672/
            - GOT_SECRET=${GOT_SECRET}
        volumes:
            - ${GOT_DIR}/got:/var/lib/got
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-consul
            - got-rabbitmq
            - got-mongo
