version: '2'

services:
    got-rabbitmq:
        image: rabbitmq
        hostname: got-rabbitmq
        command: rabbitmq-server
        entrypoint: ""
        volumes:
            - ${GOT_DIR}/rabbitmq/data:/var/lib/rabbitmq
            - ${GOT_DIR}/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        environment:
            - RABBITMQ_DEFAULT_USER=got
            - RABBITMQ_DEFAULT_PASS=got

    got-mongo:
        image: mongo
        volumes:
            - ${GOT_DIR}/mongo:/data/db

    got-redis:
        image: redis
        volumes:
            - ${GOT_DIR}/redis:/data

    got-influx:
        image: influxdb
        volumes:
           - ${GOT_DIR}/influx:/var/lib/influxdb
        environment:
          - INFLUXDB_DB=goterra
          - INFLUXDB_USER=goterra
          - INFLUXDB_USER_PASSWORD=goterra

    got-consul:
        image: consul
        hostname: consulnode1
        # To be remove in prod, used internally only
        ports:
            - "8400:8400"
            - "8500:8500"
        command: agent -dev -client 0.0.0.0 -log-level info

    got-traefik:
        # In production, port 8080 should not be open
        image: traefik
        ports:
                - "8080:8080"
                - "8081:80"
        volumes:
                - ${GOT_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml

    got-auth:
        image: osallou/goterra-auth
        depends_on:
            - got-consul
        environment:
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
            - GOOGLE_OAUTH2_CLIENT_ID=""
            - GOOGLE_OAUTH2_CLIENT_SECRET=""
            - AAI_OAUTH2_CLIENT_ID=""
            - AAI_OAUTH2_CLIENT_SECRET=""
            - GOT_AMQP=amqp://got:got@got-rabbitmq:5672/

        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-mongo
            - got-consul

    got-store:
        image: osallou/goterra-store
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
        depends_on:
            - got-consul
            - got-redis
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
    
    got-deploy:
        image: osallou/goterra-deploy
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_AMQP=amqp://got:got@got-rabbitmq:5672/
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
            - GOT_ACL_USER_CREATENS=1
        volumes:
            - ${GOT_DIR}/got:/var/lib/got
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-consul
            - got-rabbitmq
            - got-mongo

    got-run-agent:
        image: osallou/goterra-run-agent
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_AMQP=amqp://got:got@got-rabbitmq:5672/
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
            # Set to 1 to execute cmd in isolated container
            - GOT_DOCKER_USE=0
            - GOT_DOCKER_IMAGE=osallou/goterra-run-executor
            - GOT_DOCKER_DIR=${GOT_DIR}/got

        volumes:
            - ${GOT_DIR}/got:/var/lib/got
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
            # Enable this is using GOT_DOCKER_USE
            # - /var/run/docker.sock:/var/run/docker.sock
 
        depends_on:
            - got-consul
            - got-rabbitmq
            - got-mongo

    got-injector:
        image: osallou/goterra-injector
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-consul

    got-ui:
        image: osallou/goterra-ui
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
            - GOT_ACL_USER_CREATENS=1
            - GOOGLE_OAUTH2=1
            - AAI_OAUTH2=1
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-consul


    got-acct:
        image: osallou/goterra-acct
        environment:
            - GOT_PROXY=http://got-traefik
            - GOT_CONSUL=got-consul:8500
            - GOT_SECRET=${GOT_SECRET}
            - GOT_URL=${GOT_URL}
        volumes:
            - ${GOT_DIR}/goterra.yml:/root/goterra.yml
        depends_on:
            - got-consul
            - got-influx
